# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-evieext
Summary:    X.Org X11 Protocol evieext
Version:    1.1.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/evieext-%{version}.tar.bz2
Source100:  xorg-x11-proto-evieext.yaml
Provides:   evieext


%description
XEvIE is a X extension providing functionalities to allow a client to
intercept keyboard/mouse events, and optionally modify them or consume
them before delivery through the normal event delivery mechanisms.




%prep
%setup -q -n evieext-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_includedir}/X11/extensions/Xeviestr.h
%{_includedir}/X11/extensions/evieproto.h
%{_datadir}/pkgconfig/evieproto.pc
# << files


